In [1]:
from pathlib import Path
import os

print("Current working directory:")
print(Path.cwd())

Current working directory:
c:\Deepu D\AI-hiring-system\ml\v2\notebooks

In [2]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parents[2]

print(PROJECT_ROOT)

c:\Deepu D\AI-hiring-system

In [3]:
import pandas as pd
from pathlib import Path


CANDIDATE_PATH = (
    PROJECT_ROOT / 
    "ml/data/processed/candidates_v2.csv"
)

JOB_PATH = (
    PROJECT_ROOT /
    "ml/data/processed/naukri_jobs_matching_v2.csv"
)


print("=" * 70)
print("MATCHING DATA INSPECTION")
print("=" * 70)


# ============================================================
# LOAD
# ============================================================

candidates = pd.read_csv(CANDIDATE_PATH)
jobs = pd.read_csv(JOB_PATH)

print(f"\nCandidates: {len(candidates)}")
print(f"Jobs      : {len(jobs)}")


# ============================================================
# CANDIDATE COLUMNS
# ============================================================

print("\n" + "=" * 70)
print("CANDIDATE COLUMNS")
print("=" * 70)

print(candidates.columns.tolist())


# ============================================================
# JOB COLUMNS
# ============================================================

print("\n" + "=" * 70)
print("JOB COLUMNS")
print("=" * 70)

print(jobs.columns.tolist())


# ============================================================
# SAMPLE CANDIDATES
# ============================================================

print("\n" + "=" * 70)
print("CANDIDATE SAMPLE")
print("=" * 70)

print(
    candidates[
        [
            "candidate_resume",
            "job_role"
        ]
    ].head(5).to_string(index=False)
)


# ============================================================
# SAMPLE JOBS
# ============================================================

print("\n" + "=" * 70)
print("JOB SAMPLE")
print("=" * 70)

print(
    jobs[
        [
            "job_title",
            "job_description",
            "job_skills",
            "experience",
            "dataset_role"
        ]
    ].head(5).to_string(index=False)
)

======================================================================
MATCHING DATA INSPECTION
======================================================================

Candidates: 7034
Jobs      : 10000

======================================================================
CANDIDATE COLUMNS
======================================================================
['candidate_id', 'candidate_resume', 'job_role', 'normalized_resume', 'normalized_job_role', 'resume_word_count']

======================================================================
JOB COLUMNS
======================================================================
['job_id', 'job_title', 'company', 'job_description', 'job_skills', 'experience', 'location', 'salary', 'source', 'dataset_role', 'job_word_count', 'normalized_role', 'role_family']

======================================================================
CANDIDATE SAMPLE
======================================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       candidate_resume             job_role
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             here's a sample resume for a software engineer position, tailored to robert gomez's skills: robert gomez contact information: * phone: (555) 555-5555 * email: [rgomez@email.com](mailto:rgomez@email.com) * linkedin: linkedin.com/in/rgomez * github: github.com/rgomez summary: highly motivated and detail-oriented software engineer with expertise in c++, data structures, and system design. proficient in designing and implementing scalable software solutions with a strong focus on efficiency, reliability, and maintainability. proficient in c++ programming languages, data structures, and system design. technical skills: * programming languages: c++, java, python * data structures: arrays, linked lists, stacks, queues, trees, graphs * system design: designing scalable and efficient software systems, including architecture, data modeling, and system integration * operating systems: windows, linux, macos * development tools: git, github, jenkins, eclipse, visual studio * database: mysql, mongodb, postgresql professional experience: * software engineer, xyz corporation (2018-present) + designed and developed multiple software systems using c++ and java, resulting in a 30% reduction in development time and a 25% increase in system reliability + implemented data structures and algorithms to optimize system performance and scalability + collaborated with cross-functional teams to design and implement system integrations, resulting in a 40% reduction in system downtime * intern, abc startup (summer 2017) + contributed to the development of a machine learning platform using c++ and python + implemented data structures and algorithms to optimize system performance and scalability + assisted in the design and implementation of system integrations, resulting in a 20% reduction in system downtime education: * bachelor of science in computer science, university of [name] (2015-2018) + coursework: data structures, algorithms, computer systems, operating systems, database systems projects: * c++ library for designing scalable data structures: a c++ library for designing and implementing scalable data structures, including arrays, linked lists, stacks, and queues. * system design for a cloud-based application: a system design for a cloud-based application, including architecture, data modeling, and system integration. certifications: * certified c++ developer, c++ institute (2019) * certified system administrator, linux professional institute (2018) references: available upon request.    software engineer
Here is a professional resume for Barbara Evans: Barbara Evans Blockchain Developer Contact Information: * Email: [barbara.evans@email.com](mailto:barbara.evans@email.com) * Phone: (555) 123-4567 * LinkedIn: linkedin.com/in/barbaraevans * GitHub: github.com/barbaraevans Professional Summary: Highly motivated and detail-oriented Blockchain Developer with 5+ years of experience in designing, developing, and deploying scalable blockchain solutions using Solidity, Ethereum, and other cutting-edge technologies. Proven track record of successfully leading projects from concept to launch, with a strong focus on cryptography, security, and performance optimization. Technical Skills: * Programming languages: Solidity, JavaScript, Python, C++ * Blockchain platforms: Ethereum, Hyperledger Fabric, Corda * Cryptographic techniques: Elliptic Curve Cryptography, Hash Functions, Digital Signatures * Development tools: Truffle Suite, Web3.js, Ethers.js, Ganache * Operating Systems: Windows, macOS, Linux Professional Experience: Senior Blockchain Developer, ABC Corporation (2018-Present) * Designed and developed multiple blockchain-based applications, including a decentralized supply chain management system and a cryptocurrency exchange platform * Led a team of junior developers to implement and deploy a blockchain-based voting system for a government agency * Collaborated with cross-functional teams to integrate blockchain solutions with existing infrastructure and legacy systems * Developed and maintained a comprehensive suite of automated testing and deployment scripts using Truffle Suite and Web3.js Blockchain Developer, DEF Startups (2015-2018) * Contributed to the development of a blockchain-based identity verification platform, utilizing Elliptic Curve Cryptography and Digital Signatures * Participated in the design and implementation of a decentralized gaming platform, leveraging Ethereum's smart contract functionality * Worked closely with the founding team to launch multiple blockchain-based startups, including a cryptocurrency wallet and a decentralized marketplace Education: * Bachelor of Science in Computer Science, XYZ University (2010-2014) * Master of Science in Cryptography, ABC University (2015-2017) Achievements: * First-Place Winner, Ethereum Hackathon (2017) - Developed a decentralized social media platform using Ethereum's smart contracts and a novel use of Elliptic Curve Cryptography * Featured Speaker, Blockchain Conference (2019) - Presented a talk on "Designing Secure and Scalable Blockchain Solutions" * Published Researcher, Journal of Cryptographic Research (2018) - Published a paper on "A Novel Approach to Secure Multi-Party Computation using Homomorphic Encryption" Certifications: * Certified Blockchain Developer, Blockchain Council (2019) * Certified Cryptographic Engineer, Cryptographic Engineering Board (2018) References: Available upon request. Note: This is just a sample resume, and you should customize it to fit your own experiences and style. Remember to proofread carefully and tailor your resume to the specific job you're applying for. Good luck with your job search! Blockchain Developer
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  **Ishan** **Contact Information:** * Address: 123 Main St, Anytown, USA 12345 * Phone: 555-555-5555 * Email: [ishan@email.com](mailto:ishan@email.com) * LinkedIn: linkedin.com/in/ishan **Summary:** Highly motivated recent graduate with a strong foundation in data analysis and machine learning. Proven ability to learn quickly and adapt to new technologies. Proficient in Python, R, and SQL. Seeking an entry-level position as a Data Scientist to apply analytical skills and contribute to a team's success. **Education:** * **Bachelor's Degree in Computer Science**, XYZ University (20XX-20XX) + Coursework: Data Structures, Algorithms, Computer Systems, Machine Learning, and Database Management **Projects:** * **Predicting Customer Churn**, Kaggle Competition (20XX) + Ranked #15/500 participants with a score of 0.85 (4.8/5) + Utilized Python, scikit-learn, and pandas to build a logistic regression model + Achieved a 25% reduction in churn rate * **Movie Recommendation System**, Personal Project (20XX) + Built a content-based filtering system using Python and scikit-learn + Evaluated model performance using precision, recall, and F1-score + Achieved a precision of 0.85 and recall of 0.90 **Skills:** * Programming languages: Python, R * Data analysis and visualization tools: pandas, NumPy, Matplotlib, Seaborn, Tableau * Machine learning libraries: scikit-learn, TensorFlow * Databases: MySQL, PostgreSQL * Operating Systems: Windows, Linux **Experience:** * **Data Analyst Intern**, ABC Company (Summer 20XX) + Assisted in data cleaning and preprocessing for a marketing campaign + Created visualizations using Tableau to present findings to stakeholders + Developed a basic understanding of SQL and database management * **Teaching Assistant**, XYZ University (20XX-20XX) + Assisted in teaching data structures and algorithms courses + Developed and graded assignments and quizzes + Led study groups and provided individual support to students **Certifications:** * **Certified Data Scientist**, Data Science Council of America (20XX) * **Certified Analytics Professional**, Institute for Operations Research and the Management Sciences (20XX) **References:** Available upon request.       Data Scientist
                                                                                                                                                                                                                                                                                                                                                                                                                                                  **candidate profile: janki verma** **role:** data analyst **interview assessment:** janki verma demonstrated strong communication skills and a willingness to learn during the interview. however, there were several areas where her skills and experience did not align with the requirements of the data analyst role. **gaps in skills and experience:** 1. **data visualization**: janki was lacking proficiency in data visualization tools, which is a crucial aspect of a data analyst's role. she expressed interest in learning more about tools like tableau or power bi, but did not have hands-on experience. 2. **sql**: janki mentioned that she had not had extensive experience with sql, and her coding skills were limited to basic queries. this is a significant concern, as sql is a fundamental skill for data analysts. 3. **statistics**: janki's understanding of statistical concepts, such as regression analysis and hypothesis testing, was limited. she acknowledged the importance of these skills for data analysts but did not have a strong foundation in these areas. 4. **excel/spreadsheet analysis**: while janki was familiar with excel, she did not demonstrate advanced skills in spreadsheet analysis, such as data modeling or pivot tables. 5. **business intelligence (bi) tools**: janki was not familiar with any bi tools, which is a critical aspect of a data analyst's role. she expressed interest in learning more about tools like qlikview or oracle bi. 6. **machine learning (ml) and artificial intelligence (ai)**: janki's experience with ml and ai was limited, and she did not have a clear understanding of the concepts or applications. 7. **finance**: janki's experience in finance was limited, and she did not have a strong understanding of financial concepts, such as financial modeling or budgeting. 8. **healthcare**: janki's experience in healthcare was also limited, and she did not have a clear understanding of the industry or its specific challenges. **concerns raised during the interview:** * janki struggled with certain tasks, such as data modeling and sql queries, which raised concerns about her ability to perform the job requirements. * she was unfamiliar with several tools and technologies, including data visualization tools, bi tools, and ml/ai platforms. * janki's lack of experience in finance and healthcare raised concerns about her ability to adapt to different industries and provide context-specific insights. **potential for growth:** despite the gaps in her skills and experience, janki demonstrated a willingness to learn and grow. with further training and exposure, she has the potential to develop the necessary skills and expertise to excel in the data analyst role.         data analyst
                                                                                                                                                                                                                                                                                                Here's a sample resume for Angelica Ward: Angelica Ward Contact Information: * Email: [angelicaward@email.com](mailto:angelicaward@email.com) * Phone: 555-555-5555 * LinkedIn: linkedin.com/in/angelicaward * GitHub: github.com/angelicaward Professional Summary: Highly motivated and experienced Data Engineer with a strong background in MLOps, Big Data, and Data Warehousing. Proven track record of delivering scalable and reliable data pipelines, machine learning models, and data warehouses. Proficient in Spark, Hadoop, and other big data technologies. Passionate about leveraging data to drive business insights and growth. Technical Skills: * Programming languages: Python, Java, Scala * Big Data technologies: Spark, Hadoop, Hive, Pig * Data Warehousing: Snowflake, Redshift, Amazon Redshift * Data Engineering: Apache Beam, Apache Airflow, Docker * Machine Learning: TensorFlow, Scikit-learn, PyTorch * Operating Systems: Linux, Windows, macOS * Cloud platforms: AWS, GCP, Azure Professional Experience: Senior Data Engineer, ABC Company (2018-Present) * Designed and implemented a scalable data pipeline using Apache Beam and Apache Airflow, processing over 10TB of data daily * Developed and deployed multiple machine learning models using TensorFlow and Scikit-learn, resulting in a 25% increase in customer engagement * Led a team of 3 data engineers in designing and implementing a data warehouse using Snowflake, reducing data query time by 90% * Collaborated with cross-functional teams to integrate data into business applications, resulting in a 30% increase in sales revenue Data Engineer, DEF Startups (2015-2018) * Designed and implemented a big data architecture using Spark and Hadoop, processing over 1TB of data daily * Developed and deployed multiple data visualizations using Tableau and Power BI, resulting in a 20% increase in business insights * Collaborated with data scientists to develop and deploy machine learning models using Scikit-learn and PyTorch, resulting in a 15% increase in customer retention Education: * Master of Science in Computer Science, XYZ University (2015) * Bachelor of Science in Computer Science, ABC University (2010) Achievements: * Winner of the ABC Company Hackathon (2020) for developing a predictive model using TensorFlow and Scikit-learn * Featured speaker at the DEF Startups Data Engineering Conference (2017) on "Designing Scalable Data Pipelines using Apache Beam" * Published a research paper on "Big Data Architecture using Spark and Hadoop" in the Journal of Big Data (2016) Certifications: * Certified Data Engineer, Data Engineering Institute (2019) * Certified Big Data Professional, Big Data Institute (2018) References: Available upon request. I hope this sample resume helps! Remember to customize your own resume to fit your specific experiences and the job you're applying for.        Data Engineer


In [4]:
import pandas as pd

jobs = pd.read_csv(JOB_PATH)

print("=" * 70)
print("JOB SKILLS INSPECTION")
print("=" * 70)

print("\nTotal jobs:", len(jobs))

print("\nMissing job_skills:")
print(jobs["job_skills"].isna().sum())

print("\nEmpty job_skills:")
print(
    (jobs["job_skills"].fillna("").str.strip() == "").sum()
)

print("\nSample job skills:")
print(
    jobs[
        ["job_title", "job_skills", "experience", "role_family"]
    ].sample(20, random_state=42).to_string(index=False)
)

print("\n" + "=" * 70)
print("SKILL COUNT")
print("=" * 70)

skill_counts = (
    jobs["job_skills"]
    .fillna("")
    .apply(lambda x: len([s for s in x.split(",") if s.strip()]))
)

print(skill_counts.describe())

print("\nJobs with 0 skills:", (skill_counts == 0).sum())
print("Jobs with 1 skill :", (skill_counts == 1).sum())
print("Jobs with 2-5 skills:",
      ((skill_counts >= 2) & (skill_counts <= 5)).sum())
print("Jobs with >5 skills:", (skill_counts > 5).sum())

======================================================================
JOB SKILLS INSPECTION
======================================================================

Total jobs: 10000

Missing job_skills:
57

Empty job_skills:
57

Sample job skills:
                                                           job_title                                                                                                                                              job_skills experience  role_family
                                  Backend - Senior Software Engineer                                    Product management,Performance tuning,Backend,RDBMS,EDC,Manager Technology,Application development,Business strategy    3-5 Yrs     software
                                                  Software Developer                                                               b tech,net vb net,new products,mca,proactive,microsoft certified professional,sql,asp net    1-6 Yrs     software
                                                   Angular developer                                                                                Usage,Software services,Angular,Angular Development,Development,Software   3-10 Yrs        ar_vr
                                           Machine Learning Engineer                             Solution architecture,deep learning,continuous integration,Machine learning,Cloud,Deployment,test driven development,Python    2-7 Yrs        ml_ai
                                      Sr. Executive Mobile Developer                                                                Business Analysts,development,Architects,design,Lead Developers,SQL,Business analysis,SR    5-8 Yrs       mobile
                                     Senior Native Android Developer                                                                                  Computer science,Coding,XML,SQLite,JSON,Scrum,Unit testing,Android SDK   6-11 Yrs       mobile
                                             Sr . Software Developer                                                                      jQuery,RDBMS,Coding,MySQL,System design,Application security,MVC,Stored procedures    3-8 Yrs     software
                                                   Software Engineer                                                                                                       Software Engineer 1,Software engineering,Software    2-7 Yrs     software
                  Devops Engineer III (Python, K8, AWS, Heavy Infra)                                                                           continuous integration,cd,kubernetes,github,python,orchestration,golang,ci,cd    5-9 Yrs devops_cloud
                                        Associate Product Manager II                                     Product management,Data analysis,Manager Quality Assurance,Market research,Product design,Test cases,JIRA,Analytics   6-10 Yrs   management
                                                    Business Analyst Convincing Ability,Documentation,business analysis,Communication And Interpersonal Skills,Problem Solving Skills,Interpersonal,Analysis,Problem solving    1-4 Yrs     business
                                                        AI developer                                                                                                             HR,Artificial Intelligence,Development,Hrsd    1-2 Yrs        ml_ai
                                           Senior Software Developer                              Cloud Technologies,Unit Testing,.Net,React.Js,Dot Net Fullstack Developer,Fullstack Development,Full Stack,Net Development   5-15 Yrs     software
Full Stack Developer - Integrated Traffic Management System Platform                                                   Product management,Automation,Web services,Front end,Architecture,SOA,Coding,Configuration management    5-8 Yrs     software
                      Hiring For Angular Developer | Inspire Infosol                                                                           Visual Effects,Front end,Google Analytics,GIT,Test scripts,TDD,Consulting,SEO    3-6 Yrs        ar_vr
                                         Angular Developer with NGRX                                                                                                Angular 14,Javascript,Bootstrap,NGRX,Angular,Development   8-13 Yrs        ar_vr
                                                  Software Developer                                                              kubernetes,algorithms,openshift,docker,data structures,container,rest,enterprise structure   5-10 Yrs     software
                             Senior Software Engineer - Data Support                                                                                Pharma,Agile,Healthcare,Market research,Apache,Open source,Analytics,SQL    5-8 Yrs     software
                                              Data Platform Engineer                                        data analytics,data architecture,blueprint,data modeling,data integration,project management,gap analysis,sap sd    3-8 Yrs devops_cloud
                                        AI Machine Learning Engineer                                     ERP,orchestration,data science,Machine learning,Data structures,Data processing,Customer relationship,Team building    2-7 Yrs        ml_ai

======================================================================
SKILL COUNT
======================================================================
count    10000.000000
mean         7.724900
std          1.134702
min          0.000000
25%          8.000000
50%          8.000000
75%          8.000000
max         12.000000
Name: job_skills, dtype: float64

Jobs with 0 skills: 57
Jobs with 1 skill : 17
Jobs with 2-5 skills: 460
Jobs with >5 skills: 9466

In [10]:
candidates = pd.read_csv(CANDIDATE_PATH)

print("=" * 70)
print("CANDIDATE QUALITY INSPECTION")
print("=" * 70)

print("\nTotal candidates:", len(candidates))

# Detect interview/assessment style resumes
patterns = [
    "interview assessment",
    "gaps in skills",
    "concerns raised",
    "potential for growth",
    "candidate profile"
]

for pattern in patterns:
    count = candidates["candidate_resume"].fillna("").str.lower().str.contains(
        pattern,
        regex=False
    ).sum()

    print(f"{pattern:25} : {count}")

print("\n" + "=" * 70)
print("ROLE DISTRIBUTION")
print("=" * 70)

print(candidates["job_role"].value_counts())

print("\n" + "=" * 70)
print("SAMPLE RESUMES")
print("=" * 70)

for i, row in candidates.sample(10, random_state=42).iterrows():
    print("\n" + "-" * 70)
    print("ROLE:", row["job_role"])
    print("WORDS:", row["resume_word_count"])
    print(row["candidate_resume"][:1000])

======================================================================
CANDIDATE QUALITY INSPECTION
======================================================================

Total candidates: 7034
interview assessment      : 42
gaps in skills            : 23
concerns raised           : 275
potential for growth      : 415
candidate profile         : 352

======================================================================
ROLE DISTRIBUTION
======================================================================
job_role
Data Scientist               538
Software Engineer            480
Data Engineer                447
Data Analyst                 329
software engineer            307
data engineer                307
data scientist               287
DevOps Engineer              266
Machine Learning Engineer    265
Robotics Engineer            257
Cloud Architect              254
Blockchain Developer         251
QA Engineer                  251
Mobile App Developer         247
Full Stack Developer         246
Database Administrator       243
Cloud Engineer               240
Game Developer               238
AR/VR Developer              237
Cybersecurity Analyst        234
AI Researcher                225
System Administrator         223
data analyst                 183
UI Engineer                  130
Product Manager               86
ui engineer                   75
Software Developer            66
Business Analyst              23
Content Writer                18
Network Engineer              16
E-commerce Specialist         14
AI Engineer                   13
Cybersecurity Specialist       9
UX Designer                    9
IT Support Specialist          7
UI/UX Designer                 6
Data Architect                 5
HR Specialist                  2
Name: count, dtype: int64

======================================================================
SAMPLE RESUMES
======================================================================

----------------------------------------------------------------------
ROLE: Mobile App Developer
WORDS: 404
Here's a sample resume for Christina Williams: Christina Williams Mobile App Developer Contact Information: * Email: [christina.williams@email.com](mailto:christina.williams@email.com) * Phone: 555-555-5555 * LinkedIn: linkedin.com/in/christinawilliams * GitHub: github.com/christinawilliams Professional Summary: Highly motivated and detail-oriented Mobile App Developer with 5+ years of experience in designing and developing scalable, user-friendly mobile applications using Swift, Kotlin, and other cutting-edge technologies. Proven track record of delivering high-quality projects on time and exceeding client expectations. Skilled in API integration, mobile UI/UX design, and collaboration with cross-functional teams to drive project success. Technical Skills: * Programming languages: Swift, Kotlin, Java * Mobile platforms: iOS, Android * Development frameworks: UIKit, Android SDK, MVVM * APIs: RESTful APIs, GraphQL * UI/UX design: Sketch, Figma, Adobe XD * Agile methodologies: Scrum, Kan

----------------------------------------------------------------------
ROLE: Blockchain Developer
WORDS: 357
Here's a sample resume for Kathy Rodriguez: Kathy Rodriguez Blockchain Developer Contact Information: * Email: [kathy.rodriguez@email.com](mailto:kathy.rodriguez@email.com) * Phone: (555) 123-4567 * LinkedIn: linkedin.com/in/kathyrodriguez * GitHub: github.com/kathyrodriguez Summary: Highly skilled Blockchain Developer with 5+ years of experience in designing, developing, and deploying scalable and secure blockchain solutions using Solidity, Ethereum, and Smart Contracts. Proven expertise in cryptography, consensus algorithms, and blockchain architecture. Passionate about building decentralized applications that transform industries and improve lives. Technical Skills: * Programming languages: Solidity, JavaScript, C++, Python * Blockchain platforms: Ethereum, Hyperledger Fabric, Corda * Smart Contract development: Solidity, Vyper * Cryptography: Elliptic Curve Cryptography, Hash functions, Digital Signatures * Consensus algorithms: Proof of Work, Proof of Stake, Byzantine Fault Tolera

----------------------------------------------------------------------
ROLE: Full Stack Developer
WORDS: 334
Here's a sample resume for Amanda Lee, a Full Stack Developer candidate: Amanda Lee Full Stack Developer Contact Information: * Email: [amanda.lee@email.com](mailto:amanda.lee@email.com) * Phone: (123) 456-7890 * LinkedIn: linkedin.com/in/amandaleedeveloper * GitHub: github.com/amandalee Professional Summary: Highly motivated and experienced Full Stack Developer with 5+ years of experience in designing, developing, and deploying scalable and efficient web applications using modern front-end and back-end technologies. Skilled in CSS, JavaScript, React, and database management, with a strong passion for innovation and problem-solving. Technical Skills: * Front-end development: HTML5, CSS3, JavaScript, React, Redux * Back-end development: Node.js, Express.js, MongoDB, PostgreSQL * Database management: Database design, optimization, and administration * Version control: Git, SVN * Operating Systems: Windows, macOS, Linux * Agile methodologies: Scrum, Kanban Professional Experience: Full St

----------------------------------------------------------------------
ROLE: Data Engineer
WORDS: 409
Here's a sample resume for Miss Dominique Dunlap: Dominique Dunlap Data Engineer Contact Information: * Email: [ddunlap@email.com](mailto:ddunlap@email.com) * Phone: (123) 456-7890 * LinkedIn: linkedin.com/in/dominiquedunlap * GitHub: github.com/ddunlap Professional Summary: Highly skilled Data Engineer with 5+ years of experience in designing, developing, and deploying scalable data pipelines using MLOps, ETL, and Big Data technologies. Proven expertise in Cloud Platforms, Spark, and data warehousing. Passionate about leveraging data to drive business growth and innovation. Technical Skills: * Programming languages: Python, Java, Scala * Big Data technologies: Hadoop, Spark, Hive, Pig * Cloud Platforms: AWS, Azure, Google Cloud * Data Engineering tools: Apache Beam, Apache Flink, Apache Kafka * Data Warehousing: Snowflake, Redshift * Machine Learning: scikit-learn, TensorFlow, PyTorch * Operating Systems: Linux, Windows Professional Experience: Senior Data Engineer, ABC Corporation (2

----------------------------------------------------------------------
ROLE: Software Engineer
WORDS: 365
**Noah** **Software Engineer** **Contact Information:** * Email: [noah@email.com](mailto:noah@email.com) * Phone: 555-555-5555 * LinkedIn: linkedin.com/in/noahsoftware **Summary:** Results-driven Senior Software Engineer with 8+ years of experience in designing, developing, and deploying scalable, efficient, and maintainable software systems. Proven track record of delivering high-quality solutions with a focus on unit testing, cloud computing, and system architecture. Achieved a 4.6 rating in top-tier coding competitions, highlighting exceptional coding skills and problem-solving abilities. **Professional Experience:** **Senior Software Engineer, ABC Corporation (2018-Present)** * Designed and developed multiple large-scale software systems using Node.js, Microservices architecture, and CI/CD pipelines, resulting in 25% increase in productivity and 30% reduction in deployment time. * Led a team of 5 engineers in implementing a cloud-based e-commerce platform, utilizing AWS services, i

----------------------------------------------------------------------
ROLE: System Administrator
WORDS: 389
Here is a professional resume for Crystal Roberts: Crystal Roberts System Administrator Contact Information: * Address: 123 Main St, Anytown, USA 12345 * Phone: (555) 555-5555 * Email: [crystal.roberts@email.com](mailto:crystal.roberts@email.com) * LinkedIn: linkedin.com/in/crystalroberts Summary: Highly experienced System Administrator with over 10 years of experience in managing and maintaining complex Windows and Linux/Unix server environments. Skilled in Active Directory, Networking, and IT infrastructure management. Proven track record of resolving technical issues and improving system uptime. Seeking a challenging role as a System Administrator where I can utilize my expertise to drive business success. Technical Skills: * Operating Systems: Linux/Unix (Red Hat, Ubuntu), Windows Server (2008, 2012, 2016), Windows 10 * Networking: Cisco, Juniper, HP Switches and Routers * Active Directory: Installation, Configuration, and Management * Scripting: Bash, Python, PowerShell * Cloud Co

----------------------------------------------------------------------
ROLE: Cloud Engineer
WORDS: 441
Here's a sample resume for Chad Ramos: Chad Ramos Contact Information: * Email: [chad.ramos@email.com](mailto:chad.ramos@email.com) * Phone: (555) 123-4567 * LinkedIn: linkedin.com/in/chadramos * GitHub: github.com/chadramos Summary: Highly skilled Cloud Engineer with 5+ years of experience in designing, implementing, and managing cloud infrastructure on Amazon Web Services (AWS) and Microsoft Azure platforms. Proven track record of successfully migrating on-premises applications to the cloud, optimizing cloud costs, and architecting serverless solutions. Possesses in-depth knowledge of cloud networking, security, and compliance. Professional Summary: Results-driven Cloud Engineer with a strong background in cloud computing, passionate about leveraging cloud technologies to improve business agility, reduce costs, and enhance customer experience. Skilled in a range of cloud services, including AWS Lambda, Amazon S3, Amazon DynamoDB, Azure Functions, and Azure Blob Storage. Excellent pro

----------------------------------------------------------------------
ROLE: Data Scientist
WORDS: 376
**Sonia** **Contact Information:** * Email: [sonia@email.com](mailto:sonia@email.com) * Phone: 555-555-5555 * LinkedIn: linkedin.com/in/sonia **Summary:** Highly motivated and detail-oriented data scientist with 7 years of experience in leading teams and driving business growth through data-driven insights. Proficient in machine learning, statistical modeling, and data visualization. Proven track record of successfully delivering complex projects on time and exceeding client expectations. **Professional Experience:** **Senior Data Scientist, ABC Corporation (2018-Present)** * Led a team of 5 data scientists to develop a predictive maintenance model for industrial equipment, resulting in a 25% reduction in downtime and a 15% increase in overall efficiency * Collaborated with cross-functional teams to design and implement a data-driven marketing strategy, resulting in a 30% increase in sales and a 20% increase in customer engagement * Developed and deployed multiple machine learning mode

----------------------------------------------------------------------
ROLE: Machine Learning Engineer
WORDS: 415
Here's a sample professional resume for Christopher Murray: Christopher Murray Machine Learning Engineer Contact Information: * Email: [christopher.murray@email.com](mailto:christopher.murray@email.com) * Phone: (123) 456-7890 * LinkedIn: linkedin.com/in/christophermurrayml * GitHub: github.com/christophermurray Summary: Highly motivated and detail-oriented Machine Learning Engineer with 5+ years of experience in developing and deploying scalable machine learning models using Python. Skilled in using Scikit-learn, TensorFlow, and Hyperparameter Tuning to drive business growth and improve customer experience. Proficient in collaborating with cross-functional teams to design and implement data-driven solutions. Professional Experience: Machine Learning Engineer, ABC Corporation (2018-Present) * Developed and deployed multiple machine learning models using Scikit-learn and TensorFlow to improve customer segmentation, recommendation systems, and predictive maintenance. * Utilized Hyperpara

----------------------------------------------------------------------
ROLE: Game Developer
WORDS: 392
Here's a professional resume for Wendy Thompson DVM, Game Developer: Wendy Thompson DVM Contact Information: * Phone: (123) 456-7890 * Email: [wendy.thompson@email.com](mailto:wendy.thompson@email.com) * LinkedIn: linkedin.com/in/wendythompsondv * Portfolio: wendythompson.devfolio.com Professional Summary: Results-driven and innovative Game Developer with expertise in Unity, Unreal Engine, 3D Modeling, and Game Physics. As a veterinarian turned game developer, I bring a unique combination of technical skills and creative vision to deliver engaging and immersive gaming experiences. Proficient in designing and implementing game mechanics, environments, and characters, with a passion for pushing the boundaries of what's possible in game development. Technical Skills: * Programming languages: C#, C++, Java * Game Engines: Unity, Unreal Engine * 3D Modeling: Blender, Maya, 3ds Max * Game Physics: PhysX, Havok * Operating Systems: Windows, macOS, Linux Professional Experience: Game Developer

## OLLAMA INSPECTION

In [11]:
import sys
from pathlib import Path

# Go from ml/v2/notebooks → project root
PROJECT_ROOT = Path.cwd().resolve().parents[2]

# Add project root to Python's import path
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print("Project root:", PROJECT_ROOT)

Project root: C:\Deepu D\AI-hiring-system

In [12]:
from pathlib import Path

print("Current working directory:")
print(Path.cwd())

print("\nContents:")
for item in Path.cwd().iterdir():
    print(item.name)

Current working directory:
c:\Deepu D\AI-hiring-system\ml\v2\notebooks

Contents:
inspection.ipynb
model_exp_v2.ipynb

In [13]:
from ml.v2.llm.skill_extractor import extract_skills

In [14]:
JOB_PATH = PROJECT_ROOT / "ml" / "data" / "processed" / "naukri_jobs_matching_v2.csv"
CANDIDATE_PATH = PROJECT_ROOT / "ml" / "data" / "processed" / "candidates_matching_v2.csv"

jobs = pd.read_csv(JOB_PATH)
candidates = pd.read_csv(CANDIDATE_PATH)

print("Jobs:", len(jobs))
print("Candidates:", len(candidates))

Jobs: 10000
Candidates: 7034

In [15]:
job = jobs.iloc[0]

print("TITLE:")
print(job["job_title"])

print("\nJOB SKILLS:")
print(job["job_skills"])

print("\nDESCRIPTION:")
print(job["job_description"][:3000])

TITLE:
Unity Developer - Game Design

JOB SKILLS:
Game Design,Unity3D,Game Architecture,Animation,GUI,Algorithm,Data Structure,Scripting

DESCRIPTION:
- Minimum 2 years of working experience in game development - Expert knowledge of Unity, including experience with scripting, textures, animation, GUI styles, user session management, physics and particle systems - Experience of shipping out games on Android/ iOS and rolling out updates to them - Ability to plan and estimate timelines of new features/ releases. - Hands-on experience in optimising games for speed, performance, and experience; profiling of the game to identify cause of performance issues. - Understanding of multithreading, async and thread safe code - Awesome troubleshooting skills - Strong knowledge of architectural patterns, data structure and algorithms - Familiarity with level design and planning - Ability to communicate effectively with both technical and non-technical parties. - Experience of working in Product industry - Good understanding of client/ server interaction - Experience in working on a mobile multiplayer games on scale, will be a huge plus - Very good understanding of Android and iOS platforms - Open source contributions, interesting hobby projects.

In [ ]:
job_text = f"""
Job Title:
{job['job_title']}

Job Skills:
{job['job_skills']}

Job Description:
{job['job_description']}
"""

job_skills = extract_skills(job_text)

print("EXTRACTED SKILLS:")
for skill in job_skills:
    print("-", skill)

In [ ]:
candidate = candidates.iloc[0]

print("ROLE:")
print(candidate["job_role"])

print("\nRESUME:")
print(candidate["candidate_resume"][:3000])

ROLE:
software engineer

RESUME:
here's a sample resume for a software engineer position, tailored to robert gomez's skills: robert gomez contact information: * phone: (555) 555-5555 * email: [rgomez@email.com](mailto:rgomez@email.com) * linkedin: linkedin.com/in/rgomez * github: github.com/rgomez summary: highly motivated and detail-oriented software engineer with expertise in c++, data structures, and system design. proficient in designing and implementing scalable software solutions with a strong focus on efficiency, reliability, and maintainability. proficient in c++ programming languages, data structures, and system design. technical skills: * programming languages: c++, java, python * data structures: arrays, linked lists, stacks, queues, trees, graphs * system design: designing scalable and efficient software systems, including architecture, data modeling, and system integration * operating systems: windows, linux, macos * development tools: git, github, jenkins, eclipse, visual studio * database: mysql, mongodb, postgresql professional experience: * software engineer, xyz corporation (2018-present) + designed and developed multiple software systems using c++ and java, resulting in a 30% reduction in development time and a 25% increase in system reliability + implemented data structures and algorithms to optimize system performance and scalability + collaborated with cross-functional teams to design and implement system integrations, resulting in a 40% reduction in system downtime * intern, abc startup (summer 2017) + contributed to the development of a machine learning platform using c++ and python + implemented data structures and algorithms to optimize system performance and scalability + assisted in the design and implementation of system integrations, resulting in a 20% reduction in system downtime education: * bachelor of science in computer science, university of [name] (2015-2018) + coursework: data structures, algorithms, computer systems, operating systems, database systems projects: * c++ library for designing scalable data structures: a c++ library for designing and implementing scalable data structures, including arrays, linked lists, stacks, and queues. * system design for a cloud-based application: a system design for a cloud-based application, including architecture, data modeling, and system integration. certifications: * certified c++ developer, c++ institute (2019) * certified system administrator, linux professional institute (2018) references: available upon request.

In [ ]:
candidate_skills = extract_skills(candidate["candidate_resume"])

print("EXTRACTED SKILLS:")
for skill in candidate_skills:
    print("-", skill)

EXTRACTED SKILLS:
- c++
- java
- python
- arrays
- linked lists
- stacks
- queues
- trees
- graphs
- system design
- windows
- linux
- macos
- git
- github
- jenkins
- eclipse
- visual studio
- mysql
- mongodb
- postgresql

In [ ]:
def inspect_job(index):
    job = jobs.iloc[index]

    text = f"""
Job Title:
{job['job_title']}

Job Skills:
{job['job_skills']}

Job Description:
{job['job_description']}
"""

    print("=" * 70)
    print("JOB")
    print("=" * 70)

    print("\nTitle:")
    print(job["job_title"])

    print("\nOriginal skills:")
    print(job["job_skills"])

    print("\nExtracted skills:")
    skills = extract_skills(text)

    for skill in skills:
        print("-", skill)

    return skills

In [ ]:
skills = inspect_job(0)
skills

======================================================================
JOB
======================================================================

Title:
Unity Developer - Game Design

Original skills:
Game Design,Unity3D,Game Architecture,Animation,GUI,Algorithm,Data Structure,Scripting

Extracted skills:
- unity3d
- scripting
- algorithm
- data structure
- animation
- gui
- multithreading
- async
- thread safe code
- level design
- architectural patterns
- client/server interaction
- android
- ios
- game design
- game architecture

['unity3d',
 'scripting',
 'algorithm',
 'data structure',
 'animation',
 'gui',
 'multithreading',
 'async',
 'thread safe code',
 'level design',
 'architectural patterns',
 'client/server interaction',
 'android',
 'ios',
 'game design',
 'game architecture']

In [ ]:
inspect_job(10)
inspect_job(100)
inspect_job(500)

In [ ]:
def inspect_candidate(index):
    candidate = candidates.iloc[index]

    print("=" * 70)
    print("CANDIDATE")
    print("=" * 70)

    print("\nRole:")
    print(candidate["job_role"])

    print("\nResume:")
    print(candidate["candidate_resume"][:2000])

    print("\nExtracted skills:")

    skills = extract_skills(candidate["candidate_resume"])

    for skill in skills:
        print("-", skill)

    return skills

## Creating dataset

In [5]:
import pandas as pd

# Take a reproducible sample
jobs_1000 = jobs.sample(
    n=1000,
    random_state=42
).reset_index(drop=True)

print("Selected jobs:", len(jobs_1000))
print("\nRole family distribution:")
print(jobs_1000["role_family"].value_counts())

Selected jobs: 1000

Role family distribution:
role_family
software        301
devops_cloud     99
data             97
mobile           90
business         79
ar_vr            69
qa               67
ml_ai            50
database         47
management       39
game             30
design           19
security         13
Name: count, dtype: int64

In [6]:
jobs_test = jobs.sample(
    n=1000,
    random_state=42
).reset_index(drop=True)

candidates_test = candidates.sample(
    n=1000,
    random_state=42
).reset_index(drop=True)

print("Jobs:", len(jobs_test))
print("Candidates:", len(candidates_test))

Jobs: 1000
Candidates: 1000

In [ ]:
INPUT = "../../data/processed/naukri_jobs_normalized_v2.csv"
OUTPUT = "../../data/processed/naukri_jobs_matching_v2_1000.csv"

jobs = pd.read_csv(INPUT)

jobs_1000 = jobs.sample(
    n=1000,
    random_state=42
)

jobs_1000.to_csv(OUTPUT, index=False)

print(f"Original jobs: {len(jobs)}")
print(f"Sampled jobs: {len(jobs_1000)}")
print(f"Saved to: {OUTPUT}")

Original jobs: 10000
Sampled jobs: 1000
Saved to: ../../data/processed/naukri_jobs_matching_v2_1000.csv

In [ ]:
jobs_1000["role_family"].value_counts()

role_family
software        301
devops_cloud     99
data             97
mobile           90
business         79
ar_vr            69
qa               67
ml_ai            50
database         47
management       39
game             30
design           19
security         13
Name: count, dtype: int64

In [ ]:
print("\nJOB ROLE FAMILIES")
print(jobs_test["role_family"].value_counts())

print("\nCANDIDATE ROLES")
print(candidates_test["job_role"].value_counts())

JOB ROLE FAMILIES
role_family
software        301
devops_cloud     99
data             97
mobile           90
business         79
ar_vr            69
qa               67
ml_ai            50
database         47
management       39
game             30
design           19
security         13
Name: count, dtype: int64

CANDIDATE ROLES
job_role
Software Engineer            70
Data Scientist               61
Data Engineer                56
Data Analyst                 53
Machine Learning Engineer    47
data scientist               47
software engineer            45
data engineer                44
Mobile App Developer         42
Game Developer               41
Blockchain Developer         39
Cloud Architect              39
Robotics Engineer            38
QA Engineer                  38
Full Stack Developer         37
Cloud Engineer               32
Database Administrator       32
Cybersecurity Analyst        31
DevOps Engineer              30
System Administrator         28
AR/VR Developer              27
AI Researcher                25
data analyst                 23
ui engineer                  18
UI Engineer                  15
Product Manager              12
Software Developer            9
Business Analyst              5
E-commerce Specialist         4
Cybersecurity Specialist      2
Network Engineer              2
UX Designer                   2
Content Writer                2
IT Support Specialist         1
Data Architect                1
UI/UX Designer                1
HR Specialist                 1
Name: count, dtype: int64

In [ ]:
for i in range(10):
    job = jobs_test.iloc[i]

    text = f"""
    Job Title:
    {job['job_title']}

    Job Skills:
    {job['job_skills']}

    Job Description:
    {job['job_description']}
    """

    skills = extract_skills(text)

    print("=" * 70)
    print(f"JOB {i + 1}: {job['job_title']}")
    print("ROLE FAMILY:", job["role_family"])
    print("EXTRACTED:", skills)

ReadTimeout: HTTPConnectionPool(host='localhost', port=11434): Read timed out. (read timeout=120)

In [ ]:
import sys
from pathlib import Path
import pandas as pd
import time

PROJECT_ROOT = Path.cwd().parents[2]

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from ml.v2.llm.skill_extractor import extract_skills

In [7]:
JOB_PATH = (
    PROJECT_ROOT
    / "ml"
    / "data"
    / "processed"
    / "naukri_jobs_matching_v2.csv"
)

jobs = pd.read_csv(JOB_PATH)

print("Jobs:", len(jobs))

Jobs: 10000

In [ ]:
job = jobs.iloc[0]

job_text = f"""
Job Title:
{job['job_title']}

Job Skills:
{job['job_skills']}
"""

print(job_text)

start = time.time()

skills = extract_skills(job_text)

elapsed = time.time() - start

print("\nEXTRACTED SKILLS:")
print(skills)

print(f"\nTime: {elapsed:.2f} seconds")

Job Title:
Unity Developer - Game Design

Job Skills:
Game Design,Unity3D,Game Architecture,Animation,GUI,Algorithm,Data Structure,Scripting


EXTRACTED SKILLS:
['game design', 'unity3d', 'game architecture', 'animation', 'gui', 'algorithm', 'data structure', 'scripting']

Time: 5.75 seconds

In [ ]:
results = []

start_all = time.time()

for i in range(10):

    job = jobs.iloc[i]

    job_text = f"""
    Job Title:
    {job['job_title']}

    Job Skills:
    {job['job_skills']}
    """

    start = time.time()

    try:

        skills = extract_skills(job_text)

        elapsed = time.time() - start

        results.append({
            "job_id": job["job_id"],
            "job_title": job["job_title"],
            "role_family": job["role_family"],
            "skills": skills,
            "time_seconds": round(elapsed, 2),
            "status": "success"
        })

        print(
            f"{i + 1}/10 | "
            f"{elapsed:.1f}s | "
            f"{job['job_title']} | "
            f"{skills}"
        )

    except Exception as e:

        results.append({
            "job_id": job["job_id"],
            "job_title": job["job_title"],
            "role_family": job["role_family"],
            "skills": [],
            "time_seconds": None,
            "status": "failed"
        })

        print(
            f"{i + 1}/10 | FAILED | "
            f"{job['job_title']} | {e}"
        )

total_time = time.time() - start_all

print("\nTOTAL TIME:", round(total_time, 2), "seconds")

1/10 | 3.3s | Unity Developer - Game Design | ['game design', 'unity3d', 'game architecture', 'animation', 'gui', 'algorithm', 'data structure', 'scripting']
2/10 | 3.3s | Frontend/Angular Developer | ['html', 'javascript', 'css', 'jquery', 'git', 'devops', 'cloud', 'agile']
3/10 | 3.3s | Android Developer EG Industrials | ['rest', 'java', 'android', 'mobile development life cycle', 'json', 'communication skills', 'development life cycle', 'mobile development']
4/10 | 3.4s | Angular Developer | ['symantec', 'paloalto', 'cloud', 'siem', 'vulnerabilitymanagement', 'endpointsecurity', 'angular', 'angulardevelopment']
5/10 | FAILED | Angular Developer | HTTPConnectionPool(host='localhost', port=11434): Read timed out. (read timeout=120)
6/10 | 3.3s | Unity Developer Intern | ['version control', 'publishing', 'git', 'animation', 'gaming', 'android']
7/10 | 3.3s | Application Developer | ['application development', 'devops', 'software engineering', 'aws', 'agile methodology', 'c#', 'rest', 'python']
8/10 | 3.5s | Machine Learning Engineer Specialist | ['deep learning', 'software architecture', 'data science', 'machine learning', 'architectural design', 'manager technology', 'data processing', 'supervision']
9/10 | 3.3s | Game Developer | ['algorithms', 'c++', 'css', 'android', 'hibernate', 'game development', 'microservices', 'spring']
10/10 | 3.3s | Software Engineer- AEM Java | ['jquery', 'xml', 'jsp', 'javascript', 'workflow', 'j2ee', 'xslt', 'apache']

TOTAL TIME: 152.07 seconds

In [ ]:
results_df = pd.DataFrame(results)

results_df

,job_id,job_title,role_family,skills,time_seconds,status
0,41224919653,Unity Developer - Game Design,game,"[game design, unity3d, game architecture, anim...",3.30,success
1,160523501500,Frontend/Angular Developer,ar_vr,"[html, javascript, css, jquery, git, devops, c...",3.28,success
2,291024501918,Android Developer EG Industrials,mobile,"[rest, java, android, mobile development life ...",3.34,success
3,210921501253,Angular Developer,ar_vr,"[symantec, paloalto, cloud, siem, vulnerabilit...",3.44,success
4,181224009407,Angular Developer,ar_vr,[],NaN,failed
5,201124500955,Unity Developer Intern,game,"[version control, publishing, git, animation, ...",3.32,success
6,221124924015,Application Developer,software,"[application development, devops, software eng...",3.29,success
7,270924503644,Machine Learning Engineer Specialist,ml_ai,"[deep learning, software architecture, data sc...",3.48,success
8,170724502616,Game Developer,game,"[algorithms, c++, css, android, hibernate, gam...",3.32,success
9,290324501909,Software Engineer- AEM Java,software,"[jquery, xml, jsp, javascript, workflow, j2ee,...",3.25,success

In [ ]:
print("Successful:", (results_df["status"] == "success").sum())
print("Failed:", (results_df["status"] == "failed").sum())

print(
    "\nAverage time:",
    results_df["time_seconds"].mean()
)

Successful: 9
Failed: 1

Average time: 3.3355555555555556

## Creating normalized datasets

In [8]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parents[2]

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print("Project root:", PROJECT_ROOT)

Project root: c:\Deepu D\AI-hiring-system

In [9]:
import pandas as pd

from ml.v2.normalization.skill_parser import (
    parse_job_skills,
    extract_candidate_skills
)

JOB_PATH = PROJECT_ROOT / "ml" / "data" / "processed" / "naukri_jobs_matching_v2.csv"

CANDIDATE_PATH = PROJECT_ROOT / "ml" / "data" / "processed" / "candidates_matching_v2.csv"

jobs = pd.read_csv(JOB_PATH)
candidates = pd.read_csv(CANDIDATE_PATH)

print("Jobs:", len(jobs))
print("Candidates:", len(candidates))

Jobs: 10000
Candidates: 7034

In [ ]:
jobs["normalized_skills"] = jobs["job_skills"].apply(
    parse_job_skills
)

jobs[[
    "job_title",
    "job_skills",
    "normalized_skills"
]].head(20)

,job_title,job_skills,normalized_skills
0,Unity Developer - Game Design,"Game Design,Unity3D,Game Architecture,Animatio...","[game design, unity3d, game architecture, anim..."
1,Frontend/Angular Developer,"HTML,Javascript,CSS,jQuery,Front end,GIT,devop...","[html, javascript, css, jquery, front end, git..."
2,Android Developer EG Industrials,"rest,java,android,mobile development life cycl...","[rest, java, android, mobile development life ..."
3,Angular Developer,"Symantec,Palo Alto,Cloud,Siem,Vulnerability Ma...","[symantec, palo alto, cloud, siem, vulnerabili..."
4,Angular Developer,"Angular Development,Frontend Development,Angul...","[angular development, frontend development, an..."
5,Unity Developer Intern,"Version control,Publishing,GIT,Intern,Animatio...","[version control, publishing, git, intern, ani..."
6,Application Developer,"application development,devops,software engine...","[application development, devops, software eng..."
7,Machine Learning Engineer Specialist,"deep learning,software architecture,data scien...","[deep learning, software architecture, data sc..."
8,Game Developer,"algorithms,c++,css,android,hibernate,game deve...","[algorithms, c++, css, android, hibernate, gam..."
9,Software Engineer- AEM Java,"jQuery,XML,JSP,Javascript,Workflow,J2Ee,XSLT,A...","[jquery, xml, jsp, javascript, workflow, java ..."
10,DevOps Engineer,"continuous integration,ci,cd,cloud technologie...","[ci cd, ci, cd, cloud technologies, devops, co..."
11,Dot Net Developer,"NUnit,Backend,GIT,Coding,Analytical,devops,Agi...","[nunit, backend, git, coding, analytical, devo..."
12,NLP Engineer - Data Mining - Vellore,"Natural Language Processing,SQL,Pytorch,MACHIN...","[natural language processing, sql, pytorch, ma..."
13,SQL Developer,"assembly language,Data analysis,Six Sigma,PMP,...","[assembly language, data analysis, six sigma, ..."
14,Senior Software Test Engineer -,"System testing,XML,Javascript,Life sciences,GM...","[system testing, xml, javascript, life science..."
15,IT Project Manager,"Engineering consultancy,PMP,Interpersonal skil...","[engineering consultancy, pmp, interpersonal s..."
16,Full stack Developer ( Node and React ),"Full stack Developer ( Node and React ),Node,S...","[full stack developer ( node and react, node, ..."
17,Java Developer,"Data Structures,Spring Boot,Design Patterns,Mi...","[data structures, spring boot, design patterns..."
18,Cloud Architect,"continuous integration,golang,troubleshooting,...","[ci cd, go, troubleshooting, cloud platforms, ..."
19,Dot Net Developer,"SQL Server,ASP.Net,LINQ,Net Mvc,Net Developmen...","[sql server, asp.net, linq, net mvc, net devel..."

In [ ]:
print("Extracting candidate skills...")

candidates["candidate_skills"] = candidates["candidate_resume"].apply(
    extract_candidate_skills
)

print("Done.")

Extracting candidate skills...
Done.

In [ ]:
candidates[[
    "job_role",
    "candidate_skills"
]].head(20)

,job_role,candidate_skills
0,software engineer,"[python, java, c++, c, mysql, postgresql, mong..."
1,Blockchain Developer,"[python, c++, c, javascript, git, linux, solid..."
2,Data Scientist,"[python, sql, mysql, postgresql, machine learn..."
3,data analyst,"[sql, machine learning, artificial intelligenc..."
4,Data Engineer,"[python, java, aws, azure, gcp, docker, git, m..."
5,Cybersecurity Analyst,"[python, java, c++, c, linux]"
6,Full Stack Developer,"[javascript, react, angular, node.js, css, mys..."
7,Machine Learning Engineer,"[python, aws, git, machine learning, deep lear..."
8,data scientist,"[python, mysql, postgresql, machine learning, ..."
9,AI Researcher,"[python, java, c++, c, git, machine learning, ..."
10,AI Researcher,"[python, java, postgresql, mongodb, git, deep ..."
11,Mobile App Developer,"[java, kotlin, swift, react, git, graphql, and..."
12,QA Engineer,"[python, java, c, c#, mysql, linux]"
13,software engineer,"[python, c++, c, git, machine learning, scikit..."
14,Data Engineer,"[python, java, mongodb, aws, azure, gcp, docke..."
15,Data Scientist,"[python, sql, mysql, postgresql, mongodb, git,..."
16,Data Architect,"[sql, mysql, aws, azure, tableau, power bi, sp..."
17,Data Engineer,"[python, java, aws, git, machine learning, ten..."
18,Blockchain Developer,"[python, javascript, node.js, git, solidity, b..."
19,AR/VR Developer,"[c, c#, git]"

In [ ]:
candidates["skill_count"] = candidates["candidate_skills"].apply(len)

print(
    candidates["skill_count"].describe()
)

count    7034.000000
mean        8.475121
std         4.503157
min         0.000000
25%         5.000000
50%         8.000000
75%        11.000000
max        26.000000
Name: skill_count, dtype: float64

In [ ]:
for i in range(10):

    print("=" * 70)

    print("ROLE:", candidates.iloc[i]["job_role"])

    print(
        "SKILLS:",
        candidates.iloc[i]["candidate_skills"]
    )

======================================================================
ROLE: software engineer
SKILLS: ['python', 'java', 'c++', 'c', 'mysql', 'postgresql', 'mongodb', 'git', 'jenkins', 'machine learning', 'data structures', 'algorithms', 'system design', 'linux']
======================================================================
ROLE: Blockchain Developer
SKILLS: ['python', 'c++', 'c', 'javascript', 'git', 'linux', 'solidity', 'blockchain']
======================================================================
ROLE: Data Scientist
SKILLS: ['python', 'sql', 'mysql', 'postgresql', 'machine learning', 'tensorflow', 'scikit-learn', 'data structures', 'algorithms', 'linux', 'tableau']
======================================================================
ROLE: data analyst
SKILLS: ['sql', 'machine learning', 'artificial intelligence', 'tableau', 'power bi']
======================================================================
ROLE: Data Engineer
SKILLS: ['python', 'java', 'aws', 'azure', 'gcp', 'docker', 'git', 'machine learning', 'tensorflow', 'pytorch', 'scikit-learn', 'linux', 'tableau', 'power bi', 'spark', 'hadoop']
======================================================================
ROLE: Cybersecurity Analyst
SKILLS: ['python', 'java', 'c++', 'c', 'linux']
======================================================================
ROLE: Full Stack Developer
SKILLS: ['javascript', 'react', 'angular', 'node.js', 'css', 'mysql', 'postgresql', 'mongodb', 'git', 'data structures', 'algorithms', 'linux', 'graphql']
======================================================================
ROLE: Machine Learning Engineer
SKILLS: ['python', 'aws', 'git', 'machine learning', 'deep learning', 'tensorflow', 'scikit-learn', 'linux']
======================================================================
ROLE: data scientist
SKILLS: ['python', 'mysql', 'postgresql', 'machine learning', 'deep learning', 'tensorflow', 'pytorch', 'scikit-learn', 'algorithms', 'linux', 'tableau', 'power bi']
======================================================================
ROLE: AI Researcher
SKILLS: ['python', 'java', 'c++', 'c', 'git', 'machine learning', 'deep learning', 'tensorflow', 'pytorch', 'linux']

In [10]:
NORMALIZED_JOB_PATH = (
    PROJECT_ROOT
    / "ml"
    / "data"
    / "processed"
    / "naukri_jobs_normalized_v2.csv"
)

NORMALIZED_CANDIDATE_PATH = (
    PROJECT_ROOT
    / "ml"
    / "data"
    / "processed"
    / "candidates_normalized_v2.csv"
)

In [ ]:
import json

jobs_to_save = jobs.copy()

candidates_to_save = candidates.copy()

jobs_to_save["normalized_skills"] = jobs_to_save[
    "normalized_skills"
].apply(json.dumps)

candidates_to_save["candidate_skills"] = candidates_to_save[
    "candidate_skills"
].apply(json.dumps)

jobs_to_save.to_csv(
    NORMALIZED_JOB_PATH,
    index=False
)

candidates_to_save.to_csv(
    NORMALIZED_CANDIDATE_PATH,
    index=False
)

print("Saved:")
print(NORMALIZED_JOB_PATH)
print(NORMALIZED_CANDIDATE_PATH)

Saved:
c:\Deepu D\AI-hiring-system\ml\data\processed\naukri_jobs_normalized_v2.csv
c:\Deepu D\AI-hiring-system\ml\data\processed\candidates_normalized_v2.csv

## Pair generation

In [11]:
import pandas as pd

INPUT = "../../data/processed/candidates_normalized_v2.csv"
OUTPUT = "../../data/processed/candidates_normalized_v2_1000.csv"

candidates = pd.read_csv(INPUT)

candidates_1000 = candidates.sample(
    n=1000,
    random_state=42
).reset_index(drop=True)

candidates_1000.to_csv(OUTPUT, index=False)

print("Original candidates:", len(candidates))
print("Selected candidates:", len(candidates_1000))

print("\nRole distribution:")
print(candidates_1000["job_role"].value_counts())

Original candidates: 7034
Selected candidates: 1000

Role distribution:
job_role
Software Engineer            70
Data Scientist               61
Data Engineer                56
Data Analyst                 53
Machine Learning Engineer    47
data scientist               47
software engineer            45
data engineer                44
Mobile App Developer         42
Game Developer               41
Blockchain Developer         39
Cloud Architect              39
Robotics Engineer            38
QA Engineer                  38
Full Stack Developer         37
Cloud Engineer               32
Database Administrator       32
Cybersecurity Analyst        31
DevOps Engineer              30
System Administrator         28
AR/VR Developer              27
AI Researcher                25
data analyst                 23
ui engineer                  18
UI Engineer                  15
Product Manager              12
Software Developer            9
Business Analyst              5
E-commerce Specialist         4
Cybersecurity Specialist      2
Network Engineer              2
UX Designer                   2
Content Writer                2
IT Support Specialist         1
Data Architect                1
UI/UX Designer                1
HR Specialist                 1
Name: count, dtype: int64

In [3]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parents[2]

sys.path.insert(0, str(PROJECT_ROOT))

print(PROJECT_ROOT)

c:\Deepu D\AI-hiring-system

In [1]:
import pandas as pd

jobs = pd.read_csv(
    "../../data/processed/naukri_jobs_matching_v2_1000.csv"
)

candidates = pd.read_csv(
    "../../data/processed/candidates_normalized_v2_1000.csv"
)

In [4]:
from ml.v2.pair_generation import generate_pairs

In [5]:
CANDIDATE_PATH = "../../data/processed/candidates_normalized_v2_1000.csv"
JOB_PATH = "../../data/processed/naukri_jobs_matching_v2_1000.csv"

In [6]:
jobs = pd.read_csv(JOB_PATH)
candidates = pd.read_csv(CANDIDATE_PATH)

In [9]:
import inspect
from ml.v2.pair_generation import generate_pairs

print(inspect.signature(generate_pairs))
print(inspect.getsource(generate_pairs))

(jobs, candidates, candidates_per_job=50, random_state=42)
def generate_pairs(
    jobs,
    candidates,
    candidates_per_job=50,
    random_state=42,
):
    """
    Generate job-candidate pairs.

    Each job receives approximately `candidates_per_job`
    candidates distributed across:

        - same role family
        - related role family
        - different role family

    Returns:
        pandas.DataFrame
    """

    rng = np.random.default_rng(random_state)

    jobs = jobs.reset_index(drop=True)
    candidates = candidates.reset_index(drop=True)

    # --------------------------------------------------------
    # VALIDATION
    # --------------------------------------------------------

    required_job_columns = {
        "job_id",
        "job_title",
        "job_description",
        "job_skills",
        "role_family",
    }

    required_candidate_columns = {
        "candidate_id",
        "candidate_resume",
        "job_role",
        "role_family",
    }

    missing_jobs = required_job_columns - set(jobs.columns)
    missing_candidates = required_candidate_columns - set(candidates.columns)

    if missing_jobs:
        raise ValueError(
            f"Missing job columns: {missing_jobs}"
        )

    if missing_candidates:
        raise ValueError(
            f"Missing candidate columns: {missing_candidates}"
        )

    # --------------------------------------------------------
    # GROUP CANDIDATES BY ROLE FAMILY
    # --------------------------------------------------------

    candidate_groups = {
        family: group
        for family, group in candidates.groupby("role_family")
    }

    available_families = list(candidate_groups.keys())

    # --------------------------------------------------------
    # TARGET DISTRIBUTION
    # --------------------------------------------------------

    # Approximately:
    # 50% same family
    # 20% related family
    # 30% different family

    same_count = round(candidates_per_job * 0.50)
    related_count = round(candidates_per_job * 0.20)

    different_count = (
        candidates_per_job
        - same_count
        - related_count
    )

    # --------------------------------------------------------
    # HELPER
    # --------------------------------------------------------

    def sample_candidates(family, count):
        """
        Sample candidates from a family.

        Sampling is done with replacement so that even small
        role families can supply the requested number.
        """

        if family not in candidate_groups:
            return []

        group = candidate_groups[family]

        if len(group) == 0:
            return []

        indices = rng.integers(
            0,
            len(group),
            size=count,
        )

        return [
            group.iloc[idx]
            for idx in indices
        ]

    # --------------------------------------------------------
    # CREATE PAIR
    # --------------------------------------------------------

    def create_pair(job, candidate, pair_type):

        return {
            "job_id": job["job_id"],
            "job_title": job["job_title"],
            "job_description": job["job_description"],
            "job_skills": job["job_skills"],
            "job_role_family": job["role_family"],

            "candidate_id": candidate["candidate_id"],
            "candidate_role": candidate["job_role"],
            "candidate_resume": candidate["candidate_resume"],
            "candidate_role_family": candidate["role_family"],

            "pair_type": pair_type,
        }

    # --------------------------------------------------------
    # GENERATE
    # --------------------------------------------------------

    pairs = []

    for _, job in jobs.iterrows():

        job_family = job["role_family"]

        # ====================================================
        # SAME FAMILY
        # ====================================================

        same_candidates = sample_candidates(
            job_family,
            same_count,
        )

        for candidate in same_candidates:

            pairs.append(
                create_pair(
                    job,
                    candidate,
                    "same_family",
                )
            )

        # ====================================================
        # RELATED FAMILY
        # ====================================================

        related_families = [
            family
            for family in RELATED_FAMILIES.get(
                job_family,
                set(),
            )
            if family in candidate_groups
        ]

        if related_families:

            for _ in range(related_count):

                family = rng.choice(
                    related_families
                )

                candidate = sample_candidates(
                    family,
                    1,
                )

                if candidate:

                    pairs.append(
                        create_pair(
                            job,
                            candidate[0],
                            "related_family",
                        )
                    )

        # ====================================================
        # DIFFERENT FAMILY
        # ====================================================

        different_families = [
            family
            for family in available_families
            if (
                family != job_family
                and family not in RELATED_FAMILIES.get(
                    job_family,
                    set(),
                )
            )
        ]

        if different_families:

            for _ in range(different_count):

                family = rng.choice(
                    different_families
                )

                candidate = sample_candidates(
                    family,
                    1,
                )

                if candidate:

                    pairs.append(
                        create_pair(
                            job,
                            candidate[0],
                            "different_family",
                        )
                    )

    # --------------------------------------------------------
    # DATAFRAME
    # --------------------------------------------------------

    pairs_df = pd.DataFrame(pairs)

    # --------------------------------------------------------
    # SHUFFLE
    # --------------------------------------------------------

    if len(pairs_df) > 0:

        pairs_df = (
            pairs_df
            .sample(
                frac=1,
                random_state=random_state,
            )
            .reset_index(drop=True)
        )

    print("=" * 70)
    print("PAIR GENERATION COMPLETE")
    print("=" * 70)

    print(f"\nJobs: {len(jobs):,}")
    print(f"Candidates: {len(candidates):,}")
    print(f"Pairs: {len(pairs_df):,}")

    print("\nPair type distribution:")
    print(
        pairs_df["pair_type"]
        .value_counts()
    )

    print("\nJob family distribution:")
    print(
        pairs_df["job_role_family"]
        .value_counts()
    )

    return pairs_df

In [11]:
candidates_full = pd.read_csv(
    "../../data/processed/candidates_normalized_v2.csv"
)

print(candidates_full.columns.tolist())

['candidate_id', 'candidate_resume', 'job_role', 'normalized_resume', 'normalized_job_role', 'resume_word_count', 'normalized_role', 'candidate_skills', 'skill_count']

In [7]:
pairs = generate_pairs(
    jobs,
    candidates,
    candidates_per_job=50,
    random_state=42
)

print("Total pairs:", len(pairs))

ValueError: Missing candidate columns: {'role_family'}

In [ ]:
pairs[[
    "job_title",
    "job_role_family",
    "candidate_role",
    "candidate_role_family"
]].head(30)

,job_title,job_role_family,candidate_role,candidate_role_family
0,Backend - Senior Software Engineer,software,ui engineer,software
1,Backend - Senior Software Engineer,software,software engineer,software
2,Backend - Senior Software Engineer,software,Software Engineer,software
3,Backend - Senior Software Engineer,software,Software Engineer,software
4,Backend - Senior Software Engineer,software,ui engineer,software
5,Backend - Senior Software Engineer,software,Full Stack Developer,software
6,Backend - Senior Software Engineer,software,ui engineer,software
7,Backend - Senior Software Engineer,software,Software Engineer,software
8,Backend - Senior Software Engineer,software,Software Engineer,software
9,Backend - Senior Software Engineer,software,Software Engineer,software
10,Backend - Senior Software Engineer,software,Full Stack Developer,software
11,Backend - Senior Software Engineer,software,Full Stack Developer,software
12,Backend - Senior Software Engineer,software,Full Stack Developer,software
13,Backend - Senior Software Engineer,software,Full Stack Developer,software
14,Backend - Senior Software Engineer,software,UI Engineer,software
15,Backend - Senior Software Engineer,software,UI Engineer,software
16,Backend - Senior Software Engineer,software,Software Engineer,software
17,Backend - Senior Software Engineer,software,Software Engineer,software
18,Backend - Senior Software Engineer,software,Software Engineer,software
19,Backend - Senior Software Engineer,software,software engineer,software
20,Backend - Senior Software Engineer,software,Data Scientist,data
21,Backend - Senior Software Engineer,software,Cloud Engineer,devops_cloud
22,Backend - Senior Software Engineer,software,Cloud Engineer,devops_cloud
23,Backend - Senior Software Engineer,software,Data Engineer,data
24,Backend - Senior Software Engineer,software,Data Scientist,data
25,Backend - Senior Software Engineer,software,System Administrator,devops_cloud
26,Backend - Senior Software Engineer,software,QA Engineer,qa
27,Backend - Senior Software Engineer,software,Cybersecurity Analyst,security
28,Backend - Senior Software Engineer,software,Mobile App Developer,mobile
29,Backend - Senior Software Engineer,software,data analyst,data

In [ ]:
print(
    pairs[
        [
            "job_role_family",
            "candidate_role_family"
        ]
    ].value_counts()
)

job_role_family  candidate_role_family
software         software                 6894
                 data                     2897
data             data                     2314
devops_cloud     devops_cloud             2166
mobile           mobile                   1863
                                          ...
design           business                    5
security         business                    5
database         business                    4
game             design                      3
security         management                  3
Name: count, Length: 194, dtype: int64

In [ ]:
PAIR_PATH = (
    PROJECT_ROOT
    / "ml"
    / "data"
    / "processed"
    / "candidate_job_pairs_v2.csv"
)

pairs.to_csv(
    PAIR_PATH,
    index=False
)

print("Saved:")
print(PAIR_PATH)

Saved:
c:\Deepu D\AI-hiring-system\ml\data\processed\candidate_job_pairs_v2.csv

## Feature Generation

In [32]:
import sys
from pathlib import Path

PROJECT_ROOT = Path(r"C:\Deepu D\AI-hiring-system")

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from ml.v2.feature_generation import generate_features

print("Import successful!")

Import successful!

In [ ]:
import importlib
import ml.v2.feature_generation

importlib.reload(ml.v2.feature_generation)

from ml.v2.feature_generation import generate_features

ModuleNotFoundError: No module named 'ml'

In [33]:
import pandas as pd

pairs = pd.read_csv(
    "../../data/processed/candidate_job_pairs_v2.csv"
)

print("=" * 70)
print("LOADED EXISTING PAIRS")
print("=" * 70)

print(f"\nShape: {pairs.shape}")
print(f"Total pairs: {len(pairs):,}")

print("\nColumns:")
print(pairs.columns.tolist())


print("\nExample pairs:")
display(
    pairs[
        [
            "job_title",
            "job_role_family",
            "candidate_role",
            "candidate_role_family",
        ]
    ].head(10)
)

======================================================================
LOADED EXISTING PAIRS
======================================================================

Shape: (50000, 10)
Total pairs: 50,000

Columns:
['job_id', 'candidate_id', 'job_title', 'job_description', 'job_skills', 'job_role_family', 'candidate_role', 'candidate_skills', 'candidate_role_family', 'resume']

Example pairs:

,job_title,job_role_family,candidate_role,candidate_role_family
0,Backend - Senior Software Engineer,software,ui engineer,software
1,Backend - Senior Software Engineer,software,software engineer,software
2,Backend - Senior Software Engineer,software,Software Engineer,software
3,Backend - Senior Software Engineer,software,Software Engineer,software
4,Backend - Senior Software Engineer,software,ui engineer,software
5,Backend - Senior Software Engineer,software,Full Stack Developer,software
6,Backend - Senior Software Engineer,software,ui engineer,software
7,Backend - Senior Software Engineer,software,Software Engineer,software
8,Backend - Senior Software Engineer,software,Software Engineer,software
9,Backend - Senior Software Engineer,software,Software Engineer,software

In [37]:
features = generate_features(pairs)

print("\n" + "=" * 70)
print("FEATURE DATASET")
print("=" * 70)

print("Shape:", features.shape)

print("\nFeatures:")
print(features.columns.tolist())

Generating features...
Pairs: 50000
Computing TF-IDF text similarity...
TF-IDF vectorizer saved to: C:\Deepu D\AI-hiring-system\ml\models\tfidf_vectorizer.joblib
Generating labels...
Generating relevance scores...

======================================================================
FEATURE DATASET
======================================================================
Shape: (50000, 22)

Features:
['job_id', 'candidate_id', 'job_title', 'job_description', 'job_skills', 'job_role_family', 'candidate_role', 'candidate_skills', 'candidate_role_family', 'resume', 'skill_overlap_count', 'skill_overlap_ratio', 'candidate_skill_coverage', 'job_skill_coverage', 'skill_jaccard', 'role_similarity', 'candidate_experience', 'required_experience', 'experience_gap', 'text_similarity', 'label', 'relevance_score']

In [30]:
from pathlib import Path

project = Path(r"C:\Deepu D\AI-hiring-system")

matches = list(project.rglob("*.joblib"))

for x in matches:
    print(x)

C:\Deepu D\AI-hiring-system\ml\models\job_matcher.joblib
C:\Deepu D\AI-hiring-system\ml\models\tfidf_vectorizer.joblib
C:\Deepu D\AI-hiring-system\ml\v2\models\job_matcher.joblib

In [19]:
print("\nLABEL DISTRIBUTION")
print(features["label"].value_counts())

print("\nLABEL PERCENTAGES")
print(
    features["label"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

LABEL DISTRIBUTION
label
0    39419
1    10581
Name: count, dtype: int64

LABEL PERCENTAGES
label
0    78.84
1    21.16
Name: proportion, dtype: float64

In [21]:
positive = features[
    features["label"] == 1
].sample(
    min(10, (features["label"] == 1).sum()),
    random_state=42
)

negative = features[
    features["label"] == 0
].sample(
    min(10, (features["label"] == 0).sum()),
    random_state=42
)

In [22]:
print("=" * 70)
print("POSITIVE EXAMPLES")
print("=" * 70)

print(
    positive[
        [
            "job_title",
            "candidate_role",
            "job_skill_coverage",
            "skill_jaccard",
            "role_similarity",
            "text_similarity",
            "label",
        ]
    ].to_string(index=False)
)

======================================================================
POSITIVE EXAMPLES
======================================================================
                                   job_title        candidate_role  job_skill_coverage  skill_jaccard  role_similarity  text_similarity  label
             Senior DevOps Engineer - SecPod  System Administrator               0.125       0.100000         0.000000         0.191332      1
              Frontend Software Engineer - 2     Software Engineer               0.125       0.038462         0.400000         0.147049      1
         Software Engineer - C # Development     Software Engineer               0.125       0.031250         0.333333         0.002626      1
                               Data Engineer        data scientist               0.250       0.133333         0.333333         0.091869      1
                             DevOps Engineer       DevOps Engineer               0.000       0.000000         1.000000         0.106592      1
                              Data Scientist        Data Scientist               0.250       0.105263         1.000000         0.149079      1
Software Development Engineer Testing (SDET)     Software Engineer               0.250       0.083333         0.400000         0.036053      1
                    iOS Mobile App Developer  Mobile App Developer               0.125       0.058824         0.750000         0.115313      1
                            Security Analyst Cybersecurity Analyst               0.250       0.181818         0.333333         0.317652      1
                  Software Engineer - DOTNET     Software Engineer               0.250       0.086957         0.500000         0.011641      1

In [23]:
print("=" * 70)
print("NEGATIVE EXAMPLES")
print("=" * 70)

print(
    negative[
        [
            "job_title",
            "candidate_role",
            "job_skill_coverage",
            "skill_jaccard",
            "role_similarity",
            "text_similarity",
            "label",
        ]
    ].to_string(index=False)
)

======================================================================
NEGATIVE EXAMPLES
======================================================================
                      job_title         candidate_role  job_skill_coverage  skill_jaccard  role_similarity  text_similarity  label
                  IOS Developer   Blockchain Developer               0.125       0.058824         0.333333         0.027205      0
Machine Learning Engineer - NLP          AI Researcher               0.125       0.071429         0.000000         0.130807      0
              Dot Net Developer   Full Stack Developer               0.125       0.050000         0.200000         0.057026      0
              Angular Developer      Software Engineer               0.125       0.040000         0.000000         0.038302      0
       Senior Software Engineer          Data Engineer               0.000       0.000000         0.250000         0.057727      0
               Business Analyst Database Administrator               0.000       0.000000         0.000000         0.049505      0
            AWS Cloud Developer          Data Engineer               0.000       0.000000         0.000000         0.219047      0
              Android Developer  Cybersecurity Analyst               0.000       0.000000         0.000000         0.000000      0
                 Data Scientist  Cybersecurity Analyst               0.000       0.000000         0.000000         0.114478      0
              Android Developer        AR/VR Developer               0.000       0.000000         0.333333         0.035387      0

In [35]:
OUTPUT = "../../data/processed/matching_features_v2_1000.csv"

features.to_csv(
    OUTPUT,
    index=False
)

print(f"\nSaved to: {OUTPUT}")

Saved to: ../../data/processed/matching_features_v2_1000.csv

In [25]:
import pandas as pd
import numpy as np

feature_cols = [
    "job_skill_coverage",
    "skill_jaccard",
    "role_similarity",
    "text_similarity"
]

print("\nFEATURE MEANS BY LABEL")
print("=" * 60)

print(
    features.groupby("label")[feature_cols]
      .mean()
      .round(4)
)

print("\nFEATURE MEDIANS BY LABEL")
print("=" * 60)

print(
    features.groupby("label")[feature_cols]
      .median()
      .round(4)
)

FEATURE MEANS BY LABEL
============================================================
       job_skill_coverage  skill_jaccard  role_similarity  text_similarity
label
0                  0.0306         0.0152           0.0681           0.0578
1                  0.1459         0.0743           0.3997           0.1227

FEATURE MEDIANS BY LABEL
============================================================
       job_skill_coverage  skill_jaccard  role_similarity  text_similarity
label
0                   0.000         0.0000           0.0000           0.0486
1                   0.125         0.0667           0.3333           0.1115

In [26]:
print("\nFEATURE DISTRIBUTION")
print("=" * 60)

for col in feature_cols:
    print(f"\n{col}")
    print(features.groupby("label")[col].describe().round(4))

FEATURE DISTRIBUTION
============================================================

job_skill_coverage
         count    mean     std  min  25%    50%   75%     max
label
0      39419.0  0.0306  0.0621  0.0  0.0  0.000  0.00  0.4286
1      10581.0  0.1459  0.1271  0.0  0.0  0.125  0.25  1.0000

skill_jaccard
         count    mean     std  min  25%     50%     75%     max
label
0      39419.0  0.0152  0.0315  0.0  0.0  0.0000  0.0000  0.2308
1      10581.0  0.0743  0.0687  0.0  0.0  0.0667  0.1111  0.4545

role_similarity
         count    mean     std  min   25%     50%     75%     max
label
0      39419.0  0.0681  0.1170  0.0  0.00  0.0000  0.1429  0.6667
1      10581.0  0.3997  0.2887  0.0  0.25  0.3333  0.6667  1.0000

text_similarity
         count    mean     std  min     25%     50%     75%     max
label
0      39419.0  0.0578  0.0393  0.0  0.0319  0.0486  0.0740  0.4052
1      10581.0  0.1227  0.0758  0.0  0.0642  0.1115  0.1643  0.5707

In [27]:
features["relevance_score"] = (
    0.35 * features["job_skill_coverage"] +
    0.20 * features["skill_jaccard"] +
    0.30 * features["role_similarity"] +
    0.15 * features["text_similarity"]
) * 100

In [28]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
    average_precision_score
)

feature_cols = [
    "job_skill_coverage",
    "skill_jaccard",
    "role_similarity",
    "text_similarity"
]

X = features[feature_cols]
y = features["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

model = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    class_weight="balanced",
    n_jobs=-1
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

print("CLASSIFICATION REPORT")
print("=" * 60)
print(classification_report(y_test, y_pred))

print("ROC-AUC:", roc_auc_score(y_test, y_prob))
print("PR-AUC:", average_precision_score(y_test, y_prob))

print("\nCONFUSION MATRIX")
print(confusion_matrix(y_test, y_pred))

print("\nFEATURE IMPORTANCE")
print(
    pd.Series(
        model.feature_importances_,
        index=feature_cols
    ).sort_values(ascending=False)
)

CLASSIFICATION REPORT
============================================================
              precision    recall  f1-score   support

           0       0.97      0.97      0.97      7884
           1       0.90      0.90      0.90      2116

    accuracy                           0.96     10000
   macro avg       0.94      0.94      0.94     10000
weighted avg       0.96      0.96      0.96     10000

ROC-AUC: 0.9925275785275915
PR-AUC: 0.9664834297172162

CONFUSION MATRIX
[[7665  219]
 [ 204 1912]]

FEATURE IMPORTANCE
role_similarity       0.462880
text_similarity       0.228429
job_skill_coverage    0.161008
skill_jaccard         0.147683
dtype: float64

## Post integration testing

In [40]:
INPUT = "../../data/processed/matching_features_v2_1000.csv"

feature_df = pd.read_csv(INPUT)

In [41]:
print(feature_df["relevance_score"].value_counts().sort_index())

relevance_score
0     17350
1      8947
2      6515
3      6607
4      4519
5      3095
6      1742
7       737
8       321
9       129
10       36
11        2
Name: count, dtype: int64

In [42]:
print(
    feature_df.groupby("relevance_score")[
        [
            "skill_overlap_ratio",
            "skill_jaccard",
            "role_similarity",
            "text_similarity"
        ]
    ].mean()
)

                 skill_overlap_ratio  skill_jaccard  role_similarity  \
relevance_score
0                           0.000021       0.000012         0.002882
1                           0.045063       0.022823         0.029191
2                           0.050294       0.024054         0.146611
3                           0.071916       0.035984         0.214605
4                           0.101851       0.051338         0.320219
5                           0.136618       0.067479         0.414761
6                           0.179573       0.090692         0.467395
7                           0.244087       0.128047         0.521521
8                           0.319693       0.174591         0.601587
9                           0.361462       0.201494         0.665412
10                          0.479167       0.285670         0.550926
11                          0.500000       0.285714         0.625000

                 text_similarity
relevance_score
0                       0.043965
1                       0.063140
2                       0.068935
3                       0.076154
4                       0.095495
5                       0.126438
6                       0.151511
7                       0.162853
8                       0.163128
9                       0.240087
10                      0.214725
11                      0.277355